name: 'GitHub Actions Weather Bot'
 
on:
  push:
  schedule:
    - cron: '0 21 * * *'

runs-on: ubuntu-latest
 steps:
  - name: 'Checkout codes'
    uses: actions/checkout@v1


- name: 'Get weather report' 
  run: bash ./weather.sh

- name: 'Send mail' 
  uses: dawidd6/action-send-mail@master 
  with:
    serveraddress: smtp.163.com
    serverport: 465
    username: ${{ secrets.MAILUSERNAME }}
    password: ${{ secrets.MAILPASSWORD }}
    subject: Weather Report
    body: file://result.html
    to: wskkkhs@163.com
    from: GitHub Actions
    content_type: text/html
